import { readFileSync } from "node:fs";
import path from "node:path";
import type { AssetManifest } from "../lib/assets.ts";
import { ROOT } from "../lib/site.ts";

export interface Redirect {
  from: string;
  to: string;
  status: 301 | 302;
}

/**
 * English URL redirects restored from the deleted Netlify configuration
 * (`_redirects` and `netlify.toml`) and from article renames in the articles repository.
 */
export const PAGE_REDIRECTS: ReadonlyArray<readonly [string, string]> = [
  ["/authors/mattt-thompson", "/authors/mattt/"],
  ["/authors/mike-lazer-walker", "/authors/em-lazer-walker/"],
  ["/reader-submissions-new-years-2013", "/new-years-2013/"],
  ["/wkwebkit", "/wkwebview/"],
  ["/swift-literal-convertible", "/swift-literals/"],
  ["/NSDateComponents", "/datecomponents/"],
  ["/nsdatecomponents", "/datecomponents/"],
  ["/nsvaluetransformer", "/valuetransformer/"],
  ["/nstemporarydirectory", "/temporary-files/"],
  ["/nsfilemanager", "/filemanager/"],
  ["/rawoptionsettype", "/optionset/"],
  ["/mirrortype", "/mirror/"],
  ["/nslocale", "/locale/"],
  ["/nscharacterset", "/characterset/"],
  ["/documentation", "/swift-documentation/"],
  ["/swift-comparison-protocols", "/equatable-and-comparable/"],
  ["/nsregularexpression", "/swift-regular-expressions/"],
  ["/nsformatter", "/formatter/"],
  ["/clang-diagnostics", "/pragma/"],
  ["/propertyWrapper", "/propertywrapper/"],
];

/** Redirects to other hosts. */
export const EXTERNAL_REDIRECTS: ReadonlyArray<readonly [string, string]> = [
  ["/swift-documentation-example/*", "https://swift-documentation-example.nshipster.com/:splat"],
  ["/*/mutableCopyWithZone:", "https://nsmutablehipster.com/:splat"],
];

/**
 * Asset URLs from the Jekyll reference build, mapped to logical asset paths.
 * Generated by `scripts/capture-reference.ts`.
 */
export function legacyAssetAliases(): Record<string, string> {
  const file = path.join(ROOT, "src/data/legacy-assets.json");
  return JSON.parse(readFileSync(file, "utf8")) as Record<string, string>;
}

export class RoutingError extends Error {}

/**
 * Builds the redirect rules for Cloudflare's `_redirects` file.
 * A redirect whose source is now a page is omitted, as Netlify did for existing files.
 * A redirect to a missing page is an error.
 */
export function redirects(assets: AssetManifest, exists: (pathname: string) => boolean): Redirect[] {
  const rules: Redirect[] = [];
  for (const [from, to] of PAGE_REDIRECTS) {
    if (exists(from)) continue;
    if (!exists(to)) throw new RoutingError(`Redirect destination ${to} (from ${from}) does not exist`);
    rules.push({ from, to, status: 301 }, { from: `${from}/`, to, status: 301 });
  }
  for (const [legacy, logical] of Object.entries(legacyAssetAliases()).sort(([a], [b]) => (a < b ? -1 : 1))) {
    // The Jekyll pipeline sometimes changed extensions, e.g. `.m4v` to `.mp4`.
    const asset = assets.find(logical) ?? assets.find(logical.replace(/\.[^./]+$/, ""));
    if (!asset) throw new RoutingError(`Legacy asset ${legacy} refers to missing asset "${logical}"`);
    rules.push({ from: legacy, to: assets.build(asset).url, status: 301 });
  }
  // Rules with wildcards come last, which Cloudflare matches more efficiently.
  for (const [from, to] of EXTERNAL_REDIRECTS) rules.push({ from, to, status: 301 });
  return rules;
}

/** Response headers for Cloudflare's `_headers` file. */
export function headers(): string {
  return `/*
  Content-Security-Policy: default-src 'self' *.nshipster.com; script-src 'self' *.nshipster.com https://*.apple-mapkit.com; style-src 'self' 'unsafe-inline'; img-src 'self' *.gravatar.com https://*.apple-mapkit.com; frame-ancestors 'none'; object-src 'none'; connect-src 'self' *.nshipster.com https://*.apple-mapkit.com; base-uri 'none'; upgrade-insecure-requests
  Referrer-Policy: same-origin
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY

/assets/*
  Cache-Control: public, max-age=31536000, immutable

/_astro/*
  Cache-Control: public, max-age=31536000, immutable

/feed.xml
  Content-Type: application/atom+xml; charset=utf-8

/site.webmanifest
  Content-Type: application/manifest+json; charset=utf-8

/.well-known/site.webmanifest
  Content-Type: application/manifest+json; charset=utf-8
`;
}
