title: NSHipster
permalink: /:title/

twitter: 629523445
facebook: 418545184954768
google: 105091289906267717942
issn: 2373-9800

author:
  name: Mattt
  email: mattt@nshipster.com
  url: /authors/mattt

markdown: NSHipsterProcessor
highlighter: rouge

kramdown:
  parse_block_html: true
  parse_span_html: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "translators"
    values:
      layout: "translator"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "assets/css"
    values:
      stylesheet: true
  - scope:
      path: "assets/fonts"
    values:
      font: true
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/js"
    values:
      javascript: true

groups:
  - Cocoa
  - Swift
  - Xcode
  - Open Source
  - Miscellaneous
  - Trivia
  - Objective-C

include: [".well-known"]

exclude:
  - README*
  - LICENSE*
  - Gemfile*
  - Procfile
  - Rakefile
  - rakelib/
  - netlify.toml
  - _redirects

assets:
  source_maps: false
  compression: true
  defaults:
    js: { integrity: true }
    css: { integrity: true }
    img: { integrity: true }

jekyll_tidy:
  exclude:
    - robots.txt
    - humans.txt
